name: Github CI
on:
  # Configura servidor de CI para executar o pipeline de tarefas abaixo (jobs) quando testando
  # um push ou pull request for realizado tendo como alvo a branch main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest # Os comandos serão executados em um sistema operacional Linux

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 # Faz o checkout do código recebido

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      - name: Setup dependencies
        run: npm install

      - name: Build
        run: npm run build
        working-directory: ./codigo/web

      - name: Unit Test
        run: npm run test # Executada os testes de unidade
