version: '3'
services:
#  app:
#    build: .
#    entrypoint: .docker/entrypoint.sh
#    container_name: race_engineering_api
#    restart: always
#    ports:
#      - '8000:8000'
#    volumes:
#      - .:/home/node/app
#    depends_on:
#      - db
  db:
    build: .docker/postgres
    container_name: race_engineering_db
    restart: always
    tty: true
    ports:
      - '5433:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=race_engineering
